/**
 * Official 2026 NCAA College Football FBS Teams & Conferences
 * Strictly 2026 Conference Alignments
 */

const TEAMS_2026 = [
  // ==================== SEC (16 TEAMS) ====================
  { id: 'alabama', name: 'Alabama', nickname: 'Crimson Tide', abbreviation: 'ALA', conference: 'SEC', espnId: '333', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png', colors: { primary: '#9E1B32', secondary: '#828A8F' }, ranking: 6 },
  { id: 'arkansas', name: 'Arkansas', nickname: 'Razorbacks', abbreviation: 'ARK', conference: 'SEC', espnId: '8', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png', colors: { primary: '#9D2235', secondary: '#FFFFFF' } },
  { id: 'auburn', name: 'Auburn', nickname: 'Tigers', abbreviation: 'AUB', conference: 'SEC', espnId: '2', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png', colors: { primary: '#0C2340', secondary: '#E87722' } },
  { id: 'florida', name: 'Florida', nickname: 'Gators', abbreviation: 'FLA', conference: 'SEC', espnId: '57', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png', colors: { primary: '#0021A5', secondary: '#FA4616' } },
  { id: 'georgia', name: 'Georgia', nickname: 'Bulldogs', abbreviation: 'UGA', conference: 'SEC', espnId: '61', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png', colors: { primary: '#BA0C2F', secondary: '#000000' }, ranking: 3 },
  { id: 'kentucky', name: 'Kentucky', nickname: 'Wildcats', abbreviation: 'UK', conference: 'SEC', espnId: '96', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png', colors: { primary: '#0033A0', secondary: '#FFFFFF' } },
  { id: 'lsu', name: 'LSU', nickname: 'Tigers', abbreviation: 'LSU', conference: 'SEC', espnId: '99', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png', colors: { primary: '#461D7C', secondary: '#FDD023' }, ranking: 22 },
  { id: 'mississippi-state', name: 'Mississippi State', nickname: 'Bulldogs', abbreviation: 'MSST', conference: 'SEC', espnId: '344', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png', colors: { primary: '#660000', secondary: '#FFFFFF' } },
  { id: 'missouri', name: 'Missouri', nickname: 'Tigers', abbreviation: 'MIZ', conference: 'SEC', espnId: '142', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png', colors: { primary: '#F1B82D', secondary: '#000000' } },
  { id: 'oklahoma', name: 'Oklahoma', nickname: 'Sooners', abbreviation: 'OU', conference: 'SEC', espnId: '201', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png', colors: { primary: '#841617', secondary: '#FDF9D8' } },
  { id: 'ole-miss', name: 'Ole Miss', nickname: 'Rebels', abbreviation: 'MISS', conference: 'SEC', espnId: '145', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png', colors: { primary: '#13294B', secondary: '#CE1126' }, ranking: 11 },
  { id: 'south-carolina', name: 'South Carolina', nickname: 'Gamecocks', abbreviation: 'SC', conference: 'SEC', espnId: '2579', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png', colors: { primary: '#73000A', secondary: '#000000' }, ranking: 19 },
  { id: 'tennessee', name: 'Tennessee', nickname: 'Volunteers', abbreviation: 'TENN', conference: 'SEC', espnId: '2633', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png', colors: { primary: '#FF8200', secondary: '#FFFFFF' }, ranking: 9 },
  { id: 'texas', name: 'Texas', nickname: 'Longhorns', abbreviation: 'TEX', conference: 'SEC', espnId: '251', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png', colors: { primary: '#BF5700', secondary: '#FFFFFF' }, ranking: 5 },
  { id: 'texas-am', name: 'Texas A&M', nickname: 'Aggies', abbreviation: 'TA&M', conference: 'SEC', espnId: '245', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png', colors: { primary: '#500000', secondary: '#FFFFFF' }, ranking: 20 },
  { id: 'vanderbilt', name: 'Vanderbilt', nickname: 'Commodores', abbreviation: 'VAN', conference: 'SEC', espnId: '238', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png', colors: { primary: '#866D4B', secondary: '#000000' } },

  // ==================== BIG TEN (18 TEAMS) ====================
  { id: 'illinois', name: 'Illinois', nickname: 'Fighting Illini', abbreviation: 'ILL', conference: 'Big Ten', espnId: '356', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png', colors: { primary: '#13294B', secondary: '#E84A27' } },
  { id: 'indiana', name: 'Indiana', nickname: 'Hoosiers', abbreviation: 'IND', conference: 'Big Ten', espnId: '84', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png', colors: { primary: '#990000', secondary: '#EEEDEB' }, ranking: 10 },
  { id: 'iowa', name: 'Iowa', nickname: 'Hawkeyes', abbreviation: 'IOWA', conference: 'Big Ten', espnId: '2294', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png', colors: { primary: '#FFCD00', secondary: '#000000' } },
  { id: 'maryland', name: 'Maryland', nickname: 'Terrapins', abbreviation: 'MD', conference: 'Big Ten', espnId: '120', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png', colors: { primary: '#E03A3E', secondary: '#FFD520' } },
  { id: 'michigan', name: 'Michigan', nickname: 'Wolverines', abbreviation: 'MICH', conference: 'Big Ten', espnId: '130', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png', colors: { primary: '#00274C', secondary: '#FFCB05' }, ranking: 23 },
  { id: 'michigan-state', name: 'Michigan State', nickname: 'Spartans', abbreviation: 'MSU', conference: 'Big Ten', espnId: '127', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png', colors: { primary: '#18453B', secondary: '#FFFFFF' } },
  { id: 'minnesota', name: 'Minnesota', nickname: 'Golden Gophers', abbreviation: 'MINN', conference: 'Big Ten', espnId: '135', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png', colors: { primary: '#7A0019', secondary: '#FFCC33' } },
  { id: 'nebraska', name: 'Nebraska', nickname: 'Cornhuskers', abbreviation: 'NEB', conference: 'Big Ten', espnId: '158', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png', colors: { primary: '#E41C38', secondary: '#FFFFFF' } },
  { id: 'northwestern', name: 'Northwestern', nickname: 'Wildcats', abbreviation: 'NW', conference: 'Big Ten', espnId: '77', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png', colors: { primary: '#4E2A84', secondary: '#FFFFFF' } },
  { id: 'ohio-state', name: 'Ohio State', nickname: 'Buckeyes', abbreviation: 'OSU', conference: 'Big Ten', espnId: '194', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png', colors: { primary: '#BB0000', secondary: '#666666' }, ranking: 1 },
  { id: 'oregon', name: 'Oregon', nickname: 'Ducks', abbreviation: 'ORE', conference: 'Big Ten', espnId: '2483', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png', colors: { primary: '#154733', secondary: '#FEE123' }, ranking: 2 },
  { id: 'penn-state', name: 'Penn State', nickname: 'Nittany Lions', abbreviation: 'PSU', conference: 'Big Ten', espnId: '213', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png', colors: { primary: '#041E42', secondary: '#FFFFFF' }, ranking: 7 },
  { id: 'purdue', name: 'Purdue', nickname: 'Boilermakers', abbreviation: 'PUR', conference: 'Big Ten', espnId: '2509', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png', colors: { primary: '#CEB888', secondary: '#000000' } },
  { id: 'rutgers', name: 'Rutgers', nickname: 'Scarlet Knights', abbreviation: 'RUTG', conference: 'Big Ten', espnId: '164', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png', colors: { primary: '#CC0033', secondary: '#000000' } },
  { id: 'ucla', name: 'UCLA', nickname: 'Bruins', abbreviation: 'UCLA', conference: 'Big Ten', espnId: '26', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png', colors: { primary: '#2D68C4', secondary: '#F2A900' } },
  { id: 'usc', name: 'USC', nickname: 'Trojans', abbreviation: 'USC', conference: 'Big Ten', espnId: '30', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png', colors: { primary: '#990000', secondary: '#FFC72C' } },
  { id: 'washington', name: 'Washington', nickname: 'Huskies', abbreviation: 'WASH', conference: 'Big Ten', espnId: '264', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png', colors: { primary: '#4B2E83', secondary: '#B7A57A' } },
  { id: 'wisconsin', name: 'Wisconsin', nickname: 'Badgers', abbreviation: 'WIS', conference: 'Big Ten', espnId: '275', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png', colors: { primary: '#C5050C', secondary: '#FFFFFF' } },

  // ==================== ACC (17 TEAMS) ====================
  { id: 'boston-college', name: 'Boston College', nickname: 'Eagles', abbreviation: 'BC', conference: 'ACC', espnId: '103', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png', colors: { primary: '#8C2232', secondary: '#DBCCA6' } },
  { id: 'california', name: 'California', nickname: 'Golden Bears', abbreviation: 'CAL', conference: 'ACC', espnId: '25', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png', colors: { primary: '#003262', secondary: '#FDB515' } },
  { id: 'clemson', name: 'Clemson', nickname: 'Tigers', abbreviation: 'CLEM', conference: 'ACC', espnId: '228', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png', colors: { primary: '#F56600', secondary: '#522D80' }, ranking: 12 },
  { id: 'duke', name: 'Duke', nickname: 'Blue Devils', abbreviation: 'DUKE', conference: 'ACC', espnId: '150', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png', colors: { primary: '#003087', secondary: '#FFFFFF' } },
  { id: 'florida-state', name: 'Florida State', nickname: 'Seminoles', abbreviation: 'FSU', conference: 'ACC', espnId: '52', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png', colors: { primary: '#782F40', secondary: '#CEB888' } },
  { id: 'georgia-tech', name: 'Georgia Tech', nickname: 'Yellow Jackets', abbreviation: 'GT', conference: 'ACC', espnId: '59', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png', colors: { primary: '#B3A369', secondary: '#003057' } },
  { id: 'louisville', name: 'Louisville', nickname: 'Cardinals', abbreviation: 'LOU', conference: 'ACC', espnId: '97', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png', colors: { primary: '#AD0000', secondary: '#000000' } },
  { id: 'miami', name: 'Miami', nickname: 'Hurricanes', abbreviation: 'MIA', conference: 'ACC', espnId: '2390', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png', colors: { primary: '#F47321', secondary: '#005030' }, ranking: 8 },
  { id: 'nc-state', name: 'NC State', nickname: 'Wolfpack', abbreviation: 'NCST', conference: 'ACC', espnId: '152', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png', colors: { primary: '#CC0000', secondary: '#000000' } },
  { id: 'north-carolina', name: 'North Carolina', nickname: 'Tar Heels', abbreviation: 'UNC', conference: 'ACC', espnId: '153', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png', colors: { primary: '#7BAFD4', secondary: '#FFFFFF' } },
  { id: 'pittsburgh', name: 'Pittsburgh', nickname: 'Panthers', abbreviation: 'PITT', conference: 'ACC', espnId: '221', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png', colors: { primary: '#003594', secondary: '#FFB81C' } },
  { id: 'smu', name: 'SMU', nickname: 'Mustangs', abbreviation: 'SMU', conference: 'ACC', espnId: '2567', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png', colors: { primary: '#0033A0', secondary: '#C8102E' }, ranking: 15 },
  { id: 'stanford', name: 'Stanford', nickname: 'Cardinal', abbreviation: 'STAN', conference: 'ACC', espnId: '24', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png', colors: { primary: '#8C1515', secondary: '#FFFFFF' } },
  { id: 'syracuse', name: 'Syracuse', nickname: 'Orange', abbreviation: 'SYR', conference: 'ACC', espnId: '183', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png', colors: { primary: '#D44500', secondary: '#000E54' } },
  { id: 'virginia', name: 'Virginia', nickname: 'Cavaliers', abbreviation: 'UVA', conference: 'ACC', espnId: '258', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png', colors: { primary: '#232D4B', secondary: '#E57200' } },
  { id: 'virginia-tech', name: 'Virginia Tech', nickname: 'Hokies', abbreviation: 'VT', conference: 'ACC', espnId: '259', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png', colors: { primary: '#630031', secondary: '#CF4420' } },
  { id: 'wake-forest', name: 'Wake Forest', nickname: 'Demon Deacons', abbreviation: 'WAKE', conference: 'ACC', espnId: '154', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png', colors: { primary: '#9E7E38', secondary: '#000000' } },

  // ==================== BIG 12 (16 TEAMS) ====================
  { id: 'arizona', name: 'Arizona', nickname: 'Wildcats', abbreviation: 'ARIZ', conference: 'Big 12', espnId: '12', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png', colors: { primary: '#CC0033', secondary: '#003366' } },
  { id: 'arizona-state', name: 'Arizona State', nickname: 'Sun Devils', abbreviation: 'ASU', conference: 'Big 12', espnId: '9', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png', colors: { primary: '#8C1D40', secondary: '#FFC627' }, ranking: 14 },
  { id: 'baylor', name: 'Baylor', nickname: 'Bears', abbreviation: 'BAY', conference: 'Big 12', espnId: '239', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png', colors: { primary: '#154734', secondary: '#FFB81C' } },
  { id: 'byu', name: 'BYU', nickname: 'Cougars', abbreviation: 'BYU', conference: 'Big 12', espnId: '252', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png', colors: { primary: '#002E5D', secondary: '#FFFFFF' }, ranking: 17 },
  { id: 'cincinnati', name: 'Cincinnati', nickname: 'Bearcats', abbreviation: 'CIN', conference: 'Big 12', espnId: '2132', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png', colors: { primary: '#E00122', secondary: '#000000' } },
  { id: 'colorado', name: 'Colorado', nickname: 'Buffaloes', abbreviation: 'COLO', conference: 'Big 12', espnId: '38', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png', colors: { primary: '#CFB87C', secondary: '#000000' }, ranking: 18 },
  { id: 'houston', name: 'Houston', nickname: 'Cougars', abbreviation: 'HOU', conference: 'Big 12', espnId: '248', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png', colors: { primary: '#C8102E', secondary: '#FFFFFF' } },
  { id: 'iowa-state', name: 'Iowa State', nickname: 'Cyclones', abbreviation: 'ISU', conference: 'Big 12', espnId: '66', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png', colors: { primary: '#C8102E', secondary: '#F1BE48' }, ranking: 16 },
  { id: 'kansas', name: 'Kansas', nickname: 'Jayhawks', abbreviation: 'KU', conference: 'Big 12', espnId: '2305', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png', colors: { primary: '#0051BA', secondary: '#E8000D' } },
  { id: 'kansas-state', name: 'Kansas State', nickname: 'Wildcats', abbreviation: 'KSU', conference: 'Big 12', espnId: '2306', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png', colors: { primary: '#512888', secondary: '#D1D1D1' } },
  { id: 'oklahoma-state', name: 'Oklahoma State', nickname: 'Cowboys', abbreviation: 'OKST', conference: 'Big 12', espnId: '197', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png', colors: { primary: '#FF7300', secondary: '#000000' } },
  { id: 'tcu', name: 'TCU', nickname: 'Horned Frogs', abbreviation: 'TCU', conference: 'Big 12', espnId: '2628', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png', colors: { primary: '#4D1979', secondary: '#A3A9AC' } },
  { id: 'texas-tech', name: 'Texas Tech', nickname: 'Red Raiders', abbreviation: 'TTU', conference: 'Big 12', espnId: '2641', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png', colors: { primary: '#CC0000', secondary: '#000000' } },
  { id: 'ucf', name: 'UCF', nickname: 'Knights', abbreviation: 'UCF', conference: 'Big 12', espnId: '2116', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png', colors: { primary: '#BA9B37', secondary: '#000000' } },
  { id: 'utah', name: 'Utah', nickname: 'Utes', abbreviation: 'UTAH', conference: 'Big 12', espnId: '254', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png', colors: { primary: '#CC0000', secondary: '#FFFFFF' } },
  { id: 'west-virginia', name: 'West Virginia', nickname: 'Mountaineers', abbreviation: 'WVU', conference: 'Big 12', espnId: '277', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png', colors: { primary: '#002855', secondary: '#EAAA00' } },

  // ==================== GROUP OF 5 (KEY FBS SCHOOLS) ====================
  { id: 'boise-state', name: 'Boise State', nickname: 'Broncos', abbreviation: 'BSU', conference: 'Group of 5', espnId: '68', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/68.png', colors: { primary: '#0033A0', secondary: '#D64309' }, ranking: 13 },
  { id: 'memphis', name: 'Memphis', nickname: 'Tigers', abbreviation: 'MEM', conference: 'Group of 5', espnId: '235', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/235.png', colors: { primary: '#003087', secondary: '#899097' }, ranking: 25 },
  { id: 'unlv', name: 'UNLV', nickname: 'Rebels', abbreviation: 'UNLV', conference: 'Group of 5', espnId: '2439', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png', colors: { primary: '#CF0A2C', secondary: '#414042' }, ranking: 24 },
  { id: 'army', name: 'Army', nickname: 'Black Knights', abbreviation: 'ARMY', conference: 'Group of 5', espnId: '349', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/349.png', colors: { primary: '#D4AF37', secondary: '#000000' }, ranking: 21 },
  { id: 'tulane', name: 'Tulane', nickname: 'Green Wave', abbreviation: 'TULN', conference: 'Group of 5', espnId: '2655', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png', colors: { primary: '#006747', secondary: '#41748D' } },
  { id: 'usf', name: 'South Florida', nickname: 'Bulls', abbreviation: 'USF', conference: 'Group of 5', espnId: '58', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/58.png', colors: { primary: '#006747', secondary: '#CFC493' } },
  { id: 'utsa', name: 'UTSA', nickname: 'Roadrunners', abbreviation: 'UTSA', conference: 'Group of 5', espnId: '2636', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png', colors: { primary: '#0C2340', secondary: '#F15A24' } },
  { id: 'app-state', name: 'App State', nickname: 'Mountaineers', abbreviation: 'APP', conference: 'Group of 5', espnId: '2026', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png', colors: { primary: '#000000', secondary: '#FFCC00' } },
  { id: 'james-madison', name: 'James Madison', nickname: 'Dukes', abbreviation: 'JMU', conference: 'Group of 5', espnId: '256', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/256.png', colors: { primary: '#450084', secondary: '#CBB677' } },
  { id: 'liberty', name: 'Liberty', nickname: 'Flames', abbreviation: 'LIB', conference: 'Group of 5', espnId: '2335', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png', colors: { primary: '#002D62', secondary: '#C41230' } },
  { id: 'fresno-state', name: 'Fresno State', nickname: 'Bulldogs', abbreviation: 'FRES', conference: 'Group of 5', espnId: '278', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/278.png', colors: { primary: '#DB0032', secondary: '#002E6D' } },
  { id: 'san-diego-state', name: 'San Diego State', nickname: 'Aztecs', abbreviation: 'SDSU', conference: 'Group of 5', espnId: '21', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/21.png', colors: { primary: '#A6192E', secondary: '#000000' } },
  { id: 'san-jose-state', name: 'San José State', nickname: 'Spartans', abbreviation: 'SJSU', conference: 'Group of 5', espnId: '23', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/23.png', colors: { primary: '#0055A2', secondary: '#E5A823' } },
  { id: 'colorado-state', name: 'Colorado State', nickname: 'Rams', abbreviation: 'CSU', conference: 'Group of 5', espnId: '36', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/36.png', colors: { primary: '#1E4D2B', secondary: '#C8C372' } },
  { id: 'air-force', name: 'Air Force', nickname: 'Falcons', abbreviation: 'AFA', conference: 'Group of 5', espnId: '2005', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png', colors: { primary: '#003087', secondary: '#8A9EA7' } },
  { id: 'coastal-carolina', name: 'Coastal Carolina', nickname: 'Chanticleers', abbreviation: 'CCU', conference: 'Group of 5', espnId: '324', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/324.png', colors: { primary: '#006F71', secondary: '#A27752' } },
  { id: 'texas-state', name: 'Texas State', nickname: 'Bobcats', abbreviation: 'TXST', conference: 'Group of 5', espnId: '326', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/326.png', colors: { primary: '#501214', secondary: '#8D734A' } },
  { id: 'toledo', name: 'Toledo', nickname: 'Rockets', abbreviation: 'TOL', conference: 'Group of 5', espnId: '2649', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png', colors: { primary: '#002E6D', secondary: '#FFCC00' } },
  { id: 'miami-oh', name: 'Miami (OH)', nickname: 'RedHawks', abbreviation: 'M-OH', conference: 'Group of 5', espnId: '193', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/193.png', colors: { primary: '#B20000', secondary: '#000000' } },
  { id: 'western-kentucky', name: 'Western Kentucky', nickname: 'Hilltoppers', abbreviation: 'WKU', conference: 'Group of 5', espnId: '98', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/98.png', colors: { primary: '#C60C30', secondary: '#000000' } },
  { id: 'jacksonville-state', name: 'Jacksonville State', nickname: 'Gamecocks', abbreviation: 'JXST', conference: 'Group of 5', espnId: '55', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/55.png', colors: { primary: '#CC0000', secondary: '#FFFFFF' } },
  { id: 'hawaii', name: 'Hawai\'i', nickname: 'Rainbow Warriors', abbreviation: 'HAW', conference: 'Group of 5', espnId: '62', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/62.png', colors: { primary: '#024731', secondary: '#C8C8C8' } },
  { id: 'nevada', name: 'Nevada', nickname: 'Wolf Pack', abbreviation: 'NEV', conference: 'Group of 5', espnId: '2440', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png', colors: { primary: '#003366', secondary: '#807F84' } },
  { id: 'wyoming', name: 'Wyoming', nickname: 'Cowboys', abbreviation: 'WYO', conference: 'Group of 5', espnId: '2751', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png', colors: { primary: '#492F24', secondary: '#FFC425' } },

  // ==================== INDEPENDENTS & PAC-12 (2026) ====================
  { id: 'notre-dame', name: 'Notre Dame', nickname: 'Fighting Irish', abbreviation: 'ND', conference: 'Independents', espnId: '87', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png', colors: { primary: '#0C2340', secondary: '#C99700' }, ranking: 4 },
  { id: 'uconn', name: 'UConn', nickname: 'Huskies', abbreviation: 'CONN', conference: 'Independents', espnId: '41', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png', colors: { primary: '#000E2F', secondary: '#E03A3E' } },
  { id: 'umass', name: 'UMass', nickname: 'Minutemen', abbreviation: 'MASS', conference: 'Independents', espnId: '113', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/113.png', colors: { primary: '#881C1C', secondary: '#FFFFFF' } },
  { id: 'oregon-state', name: 'Oregon State', nickname: 'Beavers', abbreviation: 'ORST', conference: 'Independents', espnId: '204', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png', colors: { primary: '#DC4405', secondary: '#000000' } },
  { id: 'washington-state', name: 'Washington State', nickname: 'Cougars', abbreviation: 'WSU', conference: 'Independents', espnId: '265', logoUrl: 'https://a.espncdn.com/i/teamlogos/ncaa/500/265.png', colors: { primary: '#981E32', secondary: '#5E6A71' } }
];

module.exports = {
  TEAMS_2026
};
